export const ERROR_CODES = {
	INTERNAL_ERROR: "INTERNAL_ERROR",
	VALIDATION_FAILED: "VALIDATION_FAILED",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	CONFLICT: "CONFLICT",
	RATE_LIMITED: "RATE_LIMITED",
	BAD_REQUEST: "BAD_REQUEST",
	UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
	SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
	GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT",
	INVALID_SIGNATURE: "INVALID_SIGNATURE",
	NONCE_NOT_FOUND: "NONCE_NOT_FOUND",
	NONCE_EXPIRED: "NONCE_EXPIRED",
	SIGNER_MISMATCH: "SIGNER_MISMATCH",
	NONCE_WALLET_MISMATCH: "NONCE_WALLET_MISMATCH",
	SIWE_MESSAGE_INVALID: "SIWE_MESSAGE_INVALID",
	SIGNATURE_VERIFICATION_UNAVAILABLE: "SIGNATURE_VERIFICATION_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const HTTP_STATUS_TO_ERROR_CODE: Record<number, ErrorCode> = {
	400: ERROR_CODES.BAD_REQUEST,
	401: ERROR_CODES.UNAUTHORIZED,
	403: ERROR_CODES.FORBIDDEN,
	404: ERROR_CODES.NOT_FOUND,
	409: ERROR_CODES.CONFLICT,
	422: ERROR_CODES.UNPROCESSABLE_ENTITY,
	429: ERROR_CODES.RATE_LIMITED,
	500: ERROR_CODES.INTERNAL_ERROR,
	503: ERROR_CODES.SERVICE_UNAVAILABLE,
	504: ERROR_CODES.GATEWAY_TIMEOUT,
};

export function mapHttpStatusToErrorCode(statusCode: number): ErrorCode {
	return HTTP_STATUS_TO_ERROR_CODE[statusCode] ?? ERROR_CODES.INTERNAL_ERROR;
}
