export const ERROR_CODES = {
	INTERNAL_ERROR: "INTERNAL_ERROR",
	VALIDATION_FAILED: "VALIDATION_FAILED",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	CONFLICT: "CONFLICT",
	IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
	PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
	RATE_LIMITED: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
