export enum AddressProofType {
	UTILITY_BILL = "UTILITY_BILL",
	BANK_STATEMENT = "BANK_STATEMENT",
	TAX_RETURN = "TAX_RETURN",
	GOVERNMENT_ISSUED_LETTER = "GOVERNMENT_ISSUED_LETTER",
	LEASE_AGREEMENT = "LEASE_AGREEMENT",
	OTHER = "OTHER",
}
