export enum BusinessControllerRole {
	BENEFICIAL_OWNER = "BENEFICIAL_OWNER",
	CONTROLLING_PERSON = "CONTROLLING_PERSON",
	BENEFICIAL_OWNER_AND_CONTROLLING_PERSON = "BENEFICIAL_OWNER_AND_CONTROLLING_PERSON",
}
